version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\Build.ps1
test: off
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  server: https://ci.appveyor.com/nuget/tomaszsitarek-g2mlvqpxjr7g
  api_key:
    secure: UpY9U9w/L/GId5a0Ps2Ot6ZcUQC4aZ5pvaAkonxyz/c=
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: production
  api_key:
    secure: ik1UG2Lf3BuQXvdJws7d6nG79RABCcVLWCID9+SzMMXsQ6qOrgEvpdxhXrFEahL8
  on:
    branch: master
    appveyor_repo_tag: true